stages:
    - prebuild
    # - build
    - deploy

docker image:
    stage: prebuild
    image: docker:latest

    variables:
        DOCKER_TLS_CERTDIR: ""
    services:
        - docker:dind
    only:
        changes:
            - Dockerfile
            - requirements.txt

    script:
        - docker build -t $CI_REGISTRY/tivolicloud/docs:latest .
        - docker login $CI_REGISTRY -u gitlab-ci-token -p $CI_JOB_TOKEN
        - docker push $CI_REGISTRY/tivolicloud/docs:latest

pages:
    stage: deploy
    image: $CI_REGISTRY/tivolicloud/docs
    script:
        - mkdocs build -d public
        - deno run --unstable -A changelog-rss.ts "Changelog" docs/changelog.md
        - deno run --unstable -A changelog-rss.ts "Blender Tools Changelog" docs/blender-tools/changelog.md
    artifacts:
        paths:
            - public
# build:
#     stage: build
#     image: $CI_REGISTRY/tivolicloud/docs
#     script:
#         - mkdocs build -d public
#     artifacts:
#         paths:
#             - public

# push to s3:
#     stage: deploy
#     image: alpine:latest
#     variables:
#         S3_BUCKET: docs.tivolicloud.com
#         S3_REGION: us-east-1
#         # AWS_ACCESS_KEY_ID
#         # AWS_SECRET_ACCESS_KEY

#     needs:
#         - job: build
#           artifacts: true

#     script:
#         - apk add rclone

#         # init rclone config
#         - mkdir -p ~/.config/rclone
#         - echo "[s3]" > ~/.config/rclone/rclone.conf
#         - echo "type = s3" >> ~/.config/rclone/rclone.conf
#         - echo "provider = AWS" >> ~/.config/rclone/rclone.conf
#         - echo "env_auth = true" >> ~/.config/rclone/rclone.conf
#         - echo "region = $S3_REGION" >> ~/.config/rclone/rclone.conf
#         - echo "acl = private" >> ~/.config/rclone/rclone.conf

#         # upload content
#         - cd public
#         - rclone sync -P . s3:$S3_BUCKET
