pages:
    stage: deploy
    image: python:alpine
    script:
        - apk add git
        - pip install -r requirements.txt
        - mkdocs build -d public
    artifacts:
        paths:
            - public
