stages:
    - build
    - deploy

docker image:
    stage: build
    image: docker:latest

    variables:
        DOCKER_TLS_CERTDIR: ""
    services:
        - docker:dind
    only:
        changes:
            - Dockerfile
            - requirements.txt

    script:
        - docker build -t registry.tivolicloud.com/tivolicloud/docs:latest .
        - docker login registry.tivolicloud.com -u makitsune -p $GITLAB_TOKEN
        - docker push registry.tivolicloud.com/tivolicloud/docs:latest

pages:
    stage: deploy
    image: registry.tivolicloud.com/tivolicloud/docs
    script:
        - mkdocs build -d public
    artifacts:
        paths:
            - public
