stages:
    - build
    - deploy

docker image:
    stage: build
    image: docker:latest

    variables:
        DOCKER_TLS_CERTDIR: ""
    services:
        - docker:dind
    only:
        changes:
            - Dockerfile
            - requirements.txt

    script:
        - docker build -t $CI_REGISTRY/tivolicloud/docs:latest .
        - docker login $CI_REGISTRY -u makitsune -p $CI_JOB_TOKEN
        - docker push $CI_REGISTRY/tivolicloud/docs:latest

pages:
    stage: deploy
    image: $CI_REGISTRY/tivolicloud/docs
    script:
        - mkdocs build -d public
    artifacts:
        paths:
            - public
