stages:
    - build
    - deploy

docker image:
    stage: build
    image: docker:latest

    variables:
        DOCKER_TLS_CERTDIR: ""
    services:
        - docker:dind
    only:
        changes:
            - Dockerfile
            - requirements.txt

    script:
        - docker build -t $CI_REGISTRY/tivolicloud/docs:latest .
        - docker login $CI_REGISTRY -u gitlab-ci-token -p $CI_JOB_TOKEN
        - docker push $CI_REGISTRY/tivolicloud/docs:latest

# pages:
#     stage: deploy
#     image: $CI_REGISTRY/tivolicloud/docs
#     script:
#         - mkdocs build -d public
#     artifacts:
#         paths:
#             - public

build and push to s3:
    stage: deploy
    image: alpine:latest
    variables:
        S3_BUCKET: tivolicloud-docs
        S3_REGION: us-east-1
        # AWS_ACCESS_KEY_ID
        # AWS_SECRET_ACCESS_KEY

    script:
        # - apk add nodejs rclone aws-cli
        - apk add nodejs rclone

        - mkdocs build -d public

        # init rclone config
        - mkdir -p ~/.config/rclone
        - echo "[s3]" > ~/.config/rclone/rclone.conf
        - echo "type = s3" >> ~/.config/rclone/rclone.conf
        - echo "provider = AWS" >> ~/.config/rclone/rclone.conf
        - echo "env_auth = true" >> ~/.config/rclone/rclone.conf
        - echo "region = $S3_REGION" >> ~/.config/rclone/rclone.conf
        - echo "acl = private" >> ~/.config/rclone/rclone.conf

        # upload content
        - cd public
        - rclone sync -P . s3:$S3_BUCKET
