pages:
    stage: deploy
    image:
        name: squidfunk/mkdocs-material
        entrypoint:
            - sh
    script:
        - mkdocs build -d public
    artifacts:
        paths:
            - public
