site_name: Tivoli Cloud VR Docs
site_description: Documentation for Tivoli Cloud VR
site_author: Tivoli Cloud VR
site_url: https://tivolicloud.github.io/docs

repo_name: tivolicloud/docs
repo_url: https://github.com/tivolicloud/docs

copyright: "Copyright &copy; 2020 Tivoli Cloud VR, Inc."

nav:
    - index.md
    - changelog.md
    - ""
    - API Reference: "https://tivolicloud.github.io/apidocs"
    - Legacy Docs: "https://tivolicloud.github.io/legacydocs"
    - ""
    - Blender Tools:
          - blender-tools/changelog.md
          - blender-tools/export-a-world.md
    - ""
    - Worlds:
          - worlds/uploading-assets.md
          - worlds/host-a-world-advanced.md
    - ""
    - Avatars:
          - Unity Avatar Exporter:
                - avatars/unity-avatar-exporter/get-started.md
                - avatars/unity-avatar-exporter/changelog.md
          - avatars/avatar-standards.md
    - ""
    - Models:
          - models/custom-materials.md
    - ""
    - Scripts:
          - scripts/get-started.md
    - ""
    - Shaders:
          - shaders/shader-api-reference.md

theme:
    name: material
    language: en
    palette:
        primary: pink
        accent: pink
    font:
        text: Roboto
        code: Roboto Mono
    logo: /docs/assets/logo.svg
    favicon: /docs/assets/favicon.png
extra_css:
    - /docs/assets/custom.css
extra_javascript:
    - /docs/assets/custom.js

markdown_extensions:
    - admonition # block-styled side content like warnings
    - toc: # table of content
          permalink: true
    - pymdownx.emoji:
          emoji_index: !!python/name:materialx.emoji.twemoji
          emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.highlight # code highlighting
    - pymdownx.inlinehilite # code highlighting
    - pymdownx.superfences # code highlighting
    - pymdownx.snippets # code highlighting

plugins:
    - search
    - git-revision-date-localized
    - minify:
          minify_html: true
