site_name: Tivoli Cloud VR Docs
site_description: Documentation for Tivoli Cloud VR
site_author: Tivoli Cloud VR
site_url: https://docs.tivolicloud.com

repo_name: tivolicloud/docs
repo_url: https://git.tivolicloud.com/tivolicloud/docs

copyright: "Copyright &copy; 2020 Tivoli Cloud VR, Inc."

nav:
    - index.md
    - changelog.md
    - ""
    - Worlds:
          - worlds/blender-tools.md
          - worlds/uploading-assets.md
          - worlds/host-a-world-advanced.md
    - Avatars:
          - avatars/unity-avatar-exporter.md
          - avatars/avatar-standards.md
    - Models:
          - models/custom-materials.md
    - Scripts:
          - scripts/get-started.md
    - Shaders:
          - shaders/shader-api-reference.md
    - ""
    - API Reference: "https://apidocs.tivolicloud.com"
    - Roadmap: "https://roadmap.tivolicloud.com"
    - Legacy Docs: "https://docs.highfidelity.com"

theme:
    name: material
    language: en
    palette:
        primary: pink
        accent: pink
    font:
        text: Roboto
        code: Roboto Mono
    logo: assets/logo.svg
    favicon: assets/favicon.png
    custom_dir: overrides
extra_css:
    - assets/custom.css
extra_javascript:
    - assets/custom.js

markdown_extensions:
    - admonition # block-styled side content like warnings
    - codehilite: # code highlighting
          guess_lang: false
    - toc: # table of content
          permalink: true
plugins:
    - search
    - git-revision-date-localized
    - minify:
          minify_html: true
