name: "Docs"
on:
    push:
        branches:
            - master
jobs:
    build_and_deploy:
        name: Build and deploy
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
            - name: Build
              uses: ./. # TODO: don't build every time
              with:
                  args: mkdocs build -d public
            - name: Deploy to GitHub Pages
              uses: JamesIves/github-pages-deploy-action@3.7.1
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  BRANCH: gh-pages
                  FOLDER: public
