name: "Docs"
on:
    push:
        branches:
            - main
jobs:
    build_and_deploy:
        name: Build and deploy
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repo
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Cache requirements
              # id: cache
              uses: actions/cache@v2
              with:
                  path: ~/.cache/pip
                  key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
                  restore-keys: ${{ runner.os }}-pip-

            - name: Install system dependencies
              run: sudo apt-get install python3-setuptools python3-wheel

            - name: Install requirements
              # if: steps.cache.outputs.cache-hit != 'true'
              run: python3 -m pip install -r requirements.txt

            - name: Build docs
              shell: bash
              run: python3 -m mkdocs build -d public

            - name: Setup Deno
              uses: denoland/setup-deno@v1
              with:
                  deno-version: v1.18.2

            - name: Build changelog
              shell: bash
              run: |
                  deno run --unstable -A changelog-rss.ts "Changelog" docs/changelog.md
                  deno run --unstable -A changelog-rss.ts "Blender Tools Changelog" docs/blender-tools/changelog.md
                  deno run --unstable -A changelog-rss.ts "Unity Avatar Exporter Changelog" docs/avatars/unity-avatar-exporter/changelog.md

            - name: Deploy to GitHub Pages
              uses: JamesIves/github-pages-deploy-action@3.7.1
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  BRANCH: gh-pages
                  FOLDER: public
                  SINGLE_COMMIT: true
